# Generated by Django 3.2.2 on 2021-06-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='charge',
            new_name='position',
        ),
    ]
