# Generated by Django 3.2.2 on 2021-06-14 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_hotel_zunprunidadorganizativaid'),
        ('charge', '0001_initial'),
        ('category', '0002_alter_occupationalcategory_id_categ'),
        ('workers', '0002_rename_charge_worker_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='position',
        ),
        migrations.AddField(
            model_name='worker',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='apell1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='apell2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='cargo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='charge.charge'),
        ),
        migrations.AddField(
            model_name='worker',
            name='cat_ocup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='category.occupationalcategory'),
        ),
        migrations.AddField(
            model_name='worker',
            name='no_interno',
            field=models.CharField(default='', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='worker',
            name='unidad_org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='hotel.hotel'),
        ),
    ]
