# Generated by Django 3.2.2 on 2021-06-15 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='operador',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='workers.operador'),
        ),
    ]
