# Generated by Django 3.2.2 on 2021-05-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDeVenta',
            fields=[
                ('id_pvta', models.AutoField(primary_key=True, serialize=False)),
                ('cod_pvta', models.CharField(max_length=5, unique=True)),
                ('desc_pvta', models.CharField(blank=True, max_length=25, null=True)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
