# Generated by Django 3.2.2 on 2021-05-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellArea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeventa',
            name='id_pvta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
