# Generated by Django 3.2.2 on 2021-06-01 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_name'),
        ('sellArea', '0002_alter_puntodeventa_id_pvta'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeventa',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='hotel.hotel'),
        ),
    ]
