# Generated by Django 3.2.2 on 2021-06-01 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_name'),
        ('sellArea', '0004_alter_puntodeventa_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeventa',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_ventas', related_query_name='puntos_ventas', to='hotel.hotel'),
        ),
    ]
