# Generated by Django 3.2.2 on 2021-06-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationalCategory',
            fields=[
                ('id_categ', models.AutoField(primary_key=True, serialize=False)),
                ('cod_categ', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
