# Generated by Django 3.2.2 on 2021-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupationalcategory',
            name='id_categ',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
