# Generated by Django 3.2.2 on 2021-06-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0003_alter_currency_active'),
        ('hotel', '0004_alter_hotel_zunprunidadorganizativaid'),
        ('family', '0002_alter_family_id_grupo'),
        ('sellArea', '0006_auto_20210601_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnualSalePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currency.currency')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anualSalePlans', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'year', 'currency')},
                'index_together': {('hotel', 'year', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySalePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=218)),
                ('plan', models.FloatField()),
                ('anualSalePlan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthlySalePlans', to='salesPlan.anualsaleplan')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='family.family')),
                ('saleArea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sellArea.puntodeventa')),
            ],
            options={
                'unique_together': {('month', 'anualSalePlan', 'family', 'saleArea')},
                'index_together': {('month', 'anualSalePlan', 'family', 'saleArea')},
            },
        ),
    ]
