# Generated by Django 3.2.2 on 2021-06-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=218)),
                ('description', models.CharField(max_length=218)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
