# Generated by Django 3.2.2 on 2021-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
