# Generated by Django 3.2.2 on 2021-06-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayTime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=50)),
                ('initialDate', models.DateTimeField()),
                ('endData', models.DateTimeField()),
                ('monthOrder', models.IntegerField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('isEliminated', models.BooleanField(default=False)),
            ],
        ),
    ]
