# Generated by Django 3.2.2 on 2021-06-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_occupationalcategory_id_categ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id_cargos', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_cargo', models.CharField(max_length=5, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('activo', models.BooleanField()),
                ('fk_cat_ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='category.occupationalcategory')),
            ],
        ),
    ]
