# Generated by Django 3.2.2 on 2021-05-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('cod_grupo', models.CharField(max_length=2)),
                ('desc_grupo', models.CharField(blank=True, max_length=70, null=True)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
