# Generated by Django 3.2.2 on 2021-05-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id_grupo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
